  FUNCTION DIFCS_REES(W,EP)
! REES, STEWART & WAKER (1997), W=ES+I
    USE PRECISION
    IMPLICIT NONE
    REAL(RP) :: EP, W, TERM1, TERM2, DIFCS_REES
    TERM1 = -(W/31.5)-339*EXP(-W/2.49)
    TERM2 = LOG( (SQRT(EP)+SQRT(EP-W)) / (SQRT(EP)-SQRT(EP-W)) )
    DIFCS_REES = (EXP(TERM1)/W)*TERM2
  END FUNCTION DIFCS_REES
