#!/bin/csh

#PBS -S /bin/csh
#PBS -N pchem
#PBS -l nodes=1:ppn=1:Y21G
#PBS -j oe
#PBS -m e

cd $PBS_O_WORKDIR
pwd

# Load run data
#cp WIH_0-75nm.dat solar_fluxA.dat
#cp WIH_74-109nm.dat solar_fluxB.dat
#cp WIH_108-300nm.dat solar_fluxC.dat

date
./runpchem t 1.E6 10 1.E5 10
cp atm1D.out atm1D.in
date
