MODULE SUBS

  INTERFACE
     INTEGER FUNCTION FIND_NAME(xname,name)
       USE PRECISION
       IMPLICIT none
       CHARACTER(len=12), INTENT(IN) :: xname
       CHARACTER(len=12), INTENT(IN), DIMENSION(0:) :: name
     END FUNCTION FIND_NAME
  END INTERFACE

  INTERFACE
     FUNCTION LOCATE(xtab, x)
       USE PRECISION
       REAL(RP), DIMENSION(:), INTENT(IN) :: xtab
       REAL(RP), INTENT(IN) :: x
       INTEGER :: LOCATE
     END FUNCTION LOCATE
  END INTERFACE

  INTERFACE
     SUBROUTINE LUBKSB(a, indx, b)
       USE PRECISION
       REAL(RP), INTENT(IN), DIMENSION(:,:) :: a
       INTEGER, INTENT(IN), DIMENSION(:) :: indx
       REAL(RP), INTENT(INOUT), DIMENSION(:) :: b
     END SUBROUTINE LUBKSB
  END INTERFACE

  INTERFACE
     SUBROUTINE LUDCMP(a, indx, d)
       USE PRECISION
       REAL(RP), INTENT(INOUT), DIMENSION(:,:) :: a
       INTEGER, INTENT(OUT) :: indx(:)
       REAL(RP), INTENT(OUT) :: d
     END SUBROUTINE LUDCMP
  END INTERFACE

  INTERFACE
     SUBROUTINE GAULEG(x1, x2, x, w)
       USE PRECISION
       REAL(RP), INTENT(IN) :: x1, x2
       REAL(RP), DIMENSION(:), INTENT(OUT) :: x, w
     END SUBROUTINE GAULEG
  END INTERFACE

  INTERFACE
     SUBROUTINE INDEXX(arr,indx) 
       USE PRECISION
       IMPLICIT none
       REAL(RP), INTENT(IN), DIMENSION(:) :: arr
       INTEGER, INTENT(OUT), DIMENSION(:) :: indx
     END SUBROUTINE INDEXX
  END INTERFACE

  INTERFACE
     SUBROUTINE TRIDAG (a, b, c, r, u)
       USE PRECISION
       REAL(RP), INTENT(IN), DIMENSION(:) ::  a, b, c, r
       REAL(RP), INTENT(OUT), DIMENSION(:) ::  u
     END SUBROUTINE TRIDAG
  END INTERFACE
  
  INTERFACE
     SUBROUTINE INTRP(xtab,ytab,xval,yval)
       USE PRECISION
       REAL(RP), INTENT(IN), DIMENSION(:) :: xtab, ytab, xval
       REAL(RP), INTENT(OUT), DIMENSION(:) :: yval
     END SUBROUTINE INTRP
  END INTERFACE
 
  INTERFACE
     FUNCTION VAPOR( NAME, T)
       USE PRECISION
       IMPLICIT none
       REAL(RP), INTENT(IN) :: T
       CHARACTER(LEN=*), INTENT(IN) :: NAME
       REAL(RP) :: VAPOR
     END FUNCTION VAPOR
  END INTERFACE

  INTERFACE
     FUNCTION DIFCS_REES(W,EP)
       USE PRECISION
       IMPLICIT NONE
       REAL(RP) :: EP, W, TERM1, TERM2, DIFCS_REES
     END FUNCTION DIFCS_REES
  END INTERFACE
  
  INTERFACE
     FUNCTION DIFCS_SEC(Es,E,I)
       USE PRECISION
       IMPLICIT NONE
       REAL(RP) :: E, Es, E0, I, DIFCS_SEC
     END FUNCTION DIFCS_SEC
  END INTERFACE

  INTERFACE
     FUNCTION FIND_BIN(elctreV,elctDeV,Etest)
       USE PRECISION
       IMPLICIT NONE
       REAL(RP), INTENT(IN), DIMENSION(:) :: elctreV, elctDeV
       REAL(RP), INTENT(IN) :: Etest
       INTEGER :: FIND_BIN
     END FUNCTION FIND_BIN
  END INTERFACE
  
  INTERFACE
     SUBROUTINE WAIT
     END SUBROUTINE WAIT
  END INTERFACE

END MODULE SUBS
