#!/bin/csh

#PBS -S /bin/csh
#PBS -N pchem
#PBS -l nodes=1:ppn=1:Y21G
#PBS -j oe
#PBS -m e

cd $PBS_O_WORKDIR
pwd

# Load run data
cp ../data/solar/solar_min_0-75nm_ap.dat ../data/solar/solar_fluxA.dat
cp ../data/solar/solar_min_74-109nm_ap.dat ../data/solar/solar_fluxB.dat
cp ../data/solar/solar_min_108-300nm_ap.dat ../data/solar/solar_fluxC.dat

#cp atm1D_solar_max_hiH2O.in atm1D.in
cp pchem1D_60deg.sol pchem1D.sol

date
#cp nmolecules-noH2O.dat nmolecules.dat
./runpchem t3 1.E8 10 1.E0 20
cp atm1D.out atm1D.in

#date
#cp nmolecules-noH2O.dat nmolecules.dat
#./runpchem x2 1.E3 200 1.E1 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem x3 1.E4 200 1.E2 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem x4 1.E5 200 1.E2 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem x5 1.E6 200 1.E2 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem x6 1.E7 200 1.E2 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem y17 1.E7 200 1.E5 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem y18 1.E9 200 1.E7 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem y19 1.E9 200 1.E7 20
#cp atm1D.out atm1D.in

#date
#cp nmolecules-default.dat nmolecules.dat
#./runpchem y20 1.E9 200 1.E7 20
#cp atm1D.out atm1D.in

date
